### ISSUE TITLE
Unexpectedly large mass in Moments of Inertia

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/bonej#33] opened 2016-04-25 15:39 UTC
An uncalibrated image produces weird results when run through _Moments of Inertia: "mass" becomes unexpectedly large.
##### Steps to reproduce
1. Open bone sample image (_File > Open Samples > Bat Cochlea Volume_)
2. Run Moments of Inertia (_Plugins > BoneJ > Moments of Inertia_)
3. Press _OK_ on the Setup dialog
4. "Mass" column shows "173970 g"

**Comment by mdoube** [comment] 2018-08-06 09:39
There isn't an obvious way to deal with this. The problem is that the code operates as though you have 1cm / pixel, which is not very intuitive. It makes more sense for most of our images to assume 1 mm pixel spacing. Fixed by https://github.com/mdoube/BoneJ/commit/e8136c9102ec8f2295fc0c88adfd2fd3f38dfec1

**Closed as completed by mdoube** 2018-08-06 09:39 UTC
